apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    helm.sh/hook: pre-install, post-install
    helm.sh/hook-weight: "0"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"helm.sh/hook":"pre-install, post-install","helm.sh/hook-weight":"0"},"labels":{"app":"user-service","app.kubernetes.io/instance":"orderservice-k8s-chart"},"name":"user-service","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"user-service"}},"template":{"metadata":{"labels":{"app":"user-service"}},"spec":{"containers":[{"env":[{"name":"SPRING_PROFILES_ACTIVE","value":"default"}],"image":"872651651829.dkr.ecr.ap-northeast-2.amazonaws.com/user-service:1.0","imagePullPolicy":"Always","name":"user-service","ports":[{"containerPort":8081}]}],"imagePullSecrets":null}}}}
  creationTimestamp: "2024-12-23T03:42:45Z"
  generation: 1
  labels:
    app: user-service
    app.kubernetes.io/instance: orderservice-k8s-chart
  name: user-service
  namespace: default
  resourceVersion: "34732"
  uid: 5b162752-07d7-4633-9e5f-8995def403b8
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: user-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-service
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: default
        image: 872651651829.dkr.ecr.ap-northeast-2.amazonaws.com/user-service:1.0
        imagePullPolicy: Always
        name: user-service
        ports:
        - containerPort: 8081
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2024-12-23T03:42:45Z"
    lastUpdateTime: "2024-12-23T03:42:46Z"
    message: ReplicaSet "user-service-5f86754fcb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-12-23T03:43:10Z"
    lastUpdateTime: "2024-12-23T03:43:10Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
